"""Grounded professor discovery via OpenAlex.

Given a student's goal, find REAL professors currently active on the topic and their REAL
recent papers — grounded in OpenAlex responses, never invented. Every field on a returned
candidate is copied from an actual API payload; nothing is generated by a model here.

Why "active authors from recent works" instead of the authors endpoint: sorting authors by
citation count over-indexes on superstars/emeriti who have no bandwidth for a beginner. We
instead pull *recent works* on the topic and aggregate their authorships, which surfaces
people actually publishing on the topic right now (and their early-career co-authors — the
better-bandwidth targets for a high-schooler).

Grounded per the engine research pass (docs/engine-design.md). OpenAlex 2026 note: a free
API key is expected for reliable use (credit-metered; search calls are the most expensive).
Keyless still works at a reduced budget, which is enough for development. Set OPENALEX_API_KEY
to raise the budget. Emails are NOT resolved here — no scholarly API exposes them; that is a
separate, out-of-band step and is never guessed.
"""

from __future__ import annotations

import os
import re
from collections import Counter
from datetime import datetime, timezone

import httpx

from .models import (
    DiscoveryResult,
    Evidence,
    EvidenceKind,
    OutreachGoal,
    PaperRef,
    ProfessorCandidate,
    StudentProfile,
)

OPENALEX_BASE = "https://api.openalex.org"
_UA = "bruce-research-engine/0.1 (student research outreach; grounded, no fabrication)"


def _now() -> datetime:
    return datetime.now(timezone.utc)


def reconstruct_abstract(inverted_index: dict[str, list[int]] | None) -> str | None:
    """OpenAlex returns abstracts as an inverted index {token: [positions]}. Rebuild plaintext."""
    if not inverted_index:
        return None
    positions: list[tuple[int, str]] = []
    for token, idxs in inverted_index.items():
        for i in idxs:
            positions.append((i, token))
    positions.sort()
    text = " ".join(tok for _, tok in positions).strip()
    return text or None


def _short_id(entity_id: str | None) -> str | None:
    """'https://openalex.org/A5023888391' -> 'A5023888391'."""
    if not entity_id:
        return None
    return entity_id.rsplit("/", 1)[-1]


# Work types that are not real papers to reference in an outreach email.
_JUNK_WORK_TYPES = {
    "dataset", "supplementary-materials", "other", "peer-review", "grant",
    "reference-entry", "report-component", "editorial", "erratum", "retraction",
}


def _norm_title(title: str) -> str:
    return "".join(ch.lower() for ch in title if ch.isalnum())


def _is_preprint_doi(doi: str | None) -> bool:
    return bool(doi) and ("arxiv" in doi or "zenodo" in doi)


def _person_like(name: str | None) -> bool:
    """Filter org/consortium/garbled author entries (e.g. 'inquantio'): require >=2 name
    tokens and at least one capitalized (real people are capitalized; junk/orgs often aren't)."""
    if not name:
        return False
    tokens = [t for t in re.split(r"[^A-Za-zÀ-ɏ]+", name) if len(t) >= 2]
    return len(tokens) >= 2 and any(t[0].isupper() for t in tokens)


class OpenAlexClient:
    def __init__(self, api_key: str | None = None):
        self.api_key = api_key
        self._client = httpx.AsyncClient(
            base_url=OPENALEX_BASE, timeout=30.0, headers={"User-Agent": _UA}
        )

    async def _get(self, path: str, params: dict) -> dict:
        if self.api_key:
            params = {**params, "api_key": self.api_key}
        resp = await self._client.get(path, params=params)
        resp.raise_for_status()
        return resp.json()

    async def topics(self, search: str, per_page: int = 5) -> list[dict]:
        data = await self._get("/topics", {"search": search, "per_page": per_page})
        return data.get("results", [])

    async def works(
        self,
        *,
        filters: str | None = None,
        search: str | None = None,
        sort: str | None = None,
        per_page: int = 25,
    ) -> list[dict]:
        params: dict = {"per_page": per_page}
        if filters:
            params["filter"] = filters
        if search:
            params["search"] = search
        if sort:
            params["sort"] = sort
        data = await self._get("/works", params)
        return data.get("results", [])

    async def author(self, author_id: str) -> dict:
        return await self._get(f"/authors/{_short_id(author_id)}", {})

    async def aclose(self) -> None:
        await self._client.aclose()


async def resolve_topic(client: OpenAlexClient, interest: str) -> list[dict]:
    """Map the student's stated interest to OpenAlex Topic candidates (student confirms upstream)."""
    return await client.topics(interest, per_page=5)


async def find_candidate_seeds(
    client: OpenAlexClient,
    *,
    topic_id: str | None = None,
    search: str | None = None,
    since: str = "2024-01-01",
    max_works: int = 200,
) -> dict[str, dict]:
    """Aggregate authorships across recent works into per-author seeds.

    Use a resolved ``topic_id`` when available (precise, cheap filter); otherwise fall back
    to keyword ``search`` over recent works so arbitrary student phrasing still works.
    """
    if topic_id:
        works = await client.works(
            filters=f"topics.id:{topic_id},from_publication_date:{since},type:article",
            sort="publication_date:desc",
            per_page=min(max_works, 200),
        )
    else:
        works = await client.works(
            filters=f"from_publication_date:{since},type:article",
            search=search,
            sort="relevance_score:desc",
            per_page=min(max_works, 200),
        )
    seeds: dict[str, dict] = {}
    for w in works:
        for authorship in w.get("authorships", []):
            author = authorship.get("author") or {}
            aid = author.get("id")
            if not aid or not _person_like(author.get("display_name")):
                continue
            seed = seeds.setdefault(
                aid,
                {"author_id": aid, "name": author.get("display_name"), "count": 0,
                 "institution": None, "positions": []},
            )
            seed["count"] += 1
            seed["positions"].append(authorship.get("author_position"))
            insts = authorship.get("institutions") or []
            if insts and not seed["institution"]:
                seed["institution"] = insts[0].get("display_name")
    return seeds


async def enrich_candidate(
    client: OpenAlexClient,
    seed: dict,
    topic_display: str,
    *,
    topic_id: str | None = None,
    search_term: str | None = None,
) -> ProfessorCandidate:
    """Pull the author's stats + recent papers ON THE TOPIC and build a grounded candidate."""
    author = await client.author(seed["author_id"])
    sid = _short_id(seed["author_id"])
    # Restrict to the topic so hooks are relevant (not just the author's latest paper on
    # anything): topic-id filter when resolved, else keyword search over their works.
    if topic_id:
        recent = await client.works(
            filters=f"authorships.author.id:{sid},topics.id:{topic_id},from_publication_date:2023-01-01",
            sort="publication_date:desc",
            per_page=15,
        )
    else:
        recent = await client.works(
            filters=f"authorships.author.id:{sid},from_publication_date:2023-01-01",
            search=search_term,
            sort="publication_date:desc",
            per_page=15,
        )

    # Drop non-paper records (datasets, supplementary files, errata) and dedupe by title,
    # preferring a published DOI over an arXiv/Zenodo preprint of the same work.
    deduped: dict[str, dict] = {}
    for w in recent:
        if (w.get("type") or "") in _JUNK_WORK_TYPES:
            continue
        raw_title = (w.get("display_name") or "").strip()
        if not raw_title:
            continue
        key = _norm_title(raw_title)
        prev = deduped.get(key)
        if prev is None:
            deduped[key] = w
        elif _is_preprint_doi(prev.get("doi")) and not _is_preprint_doi(w.get("doi")):
            deduped[key] = w  # upgrade preprint -> published version

    papers: list[PaperRef] = []
    evidence: list[Evidence] = []
    for w in list(deduped.values())[:4]:
        title = (w.get("display_name") or "").strip()
        doi = w.get("doi")
        oa_pdf = (w.get("open_access") or {}).get("oa_url")  # open-access PDF (for email extraction)
        venue = ((w.get("primary_location") or {}).get("source") or {}).get("display_name")
        abstract = reconstruct_abstract(w.get("abstract_inverted_index"))
        author_names = [
            (a.get("author") or {}).get("display_name")
            for a in (w.get("authorships") or [])
            if (a.get("author") or {}).get("display_name")
        ][:8]
        papers.append(
            PaperRef(
                title=title,
                authors=author_names,
                year=w.get("publication_year"),
                venue=venue,
                doi=doi,
                url=doi or w.get("id"),
                pdf_url=oa_pdf,
                abstract_snippet=abstract if abstract else None,  # full abstract — grounding rigor
                source="openalex",
            )
        )
        evidence.append(
            Evidence(
                kind=EvidenceKind.paper,
                title=title,
                url=doi or w.get("id"),
                source="openalex",
                snippet=abstract[:200] if abstract else None,
                retrieved_at=_now(),
            )
        )

    # --- Affiliation: modal current affiliation from THIS author's own recent works. ---
    # OpenAlex last_known_institutions is noisy (it mislabels e.g. Huo); the institution
    # attributed to the author across their recent papers is a better "current" signal.
    aff_counter: Counter[str] = Counter()
    aff_ror: dict[str, str | None] = {}
    for w in recent:
        for a in w.get("authorships") or []:
            if (a.get("author") or {}).get("id") == seed["author_id"]:
                for inst in a.get("institutions") or []:
                    nm = inst.get("display_name")
                    if nm:
                        aff_counter[nm] += 1
                        aff_ror.setdefault(nm, inst.get("ror"))
    if aff_counter:
        institution = aff_counter.most_common(1)[0][0]
        institution_ror = aff_ror.get(institution)
    else:
        last_known = author.get("last_known_institutions") or []
        institution = (last_known[0].get("display_name") if last_known else None) or seed.get(
            "institution"
        ) or "Unknown"
        institution_ror = last_known[0].get("ror") if last_known else None

    stats = author.get("summary_stats") or {}
    h_index = stats.get("h_index")
    works_count = author.get("works_count")
    count = seed["count"]

    # --- Seniority + fit-gating (heuristic; h-index is absolute here, not field-relative). ---
    if h_index is None:
        seniority = "unknown"
    elif h_index >= 60:
        seniority = "titan"
    elif h_index >= 25:
        seniority = "senior"
    elif h_index >= 10:
        seniority = "mid"
    else:
        seniority = "early_career"

    depth = min(count / 5, 1.0)
    seniority_factor = {"titan": 0.30, "senior": 0.65, "mid": 1.0, "early_career": 1.0, "unknown": 0.80}[seniority]
    fit_score = round(0.55 * depth + 0.45 * seniority_factor, 2)
    recommend_send = fit_score >= 0.45 and seniority != "titan"

    fit_flags: list[str] = []
    if seniority == "titan":
        fit_flags.append(
            "Very high-profile PI — likely little bandwidth for a beginner; consider their "
            "postdocs/PhD students instead."
        )
    if seniority == "early_career":
        fit_flags.append("Early-career researcher — often more bandwidth to mentor a student.")
    if count < 2:
        fit_flags.append("Only one recent paper on this topic — confirm it's a current focus.")
    if institution == "Unknown":
        # An author we can't place at an institution is not an actionable outreach target
        # (no email, no way to verify who they are) — sink them, don't recommend sending.
        fit_score = round(fit_score * 0.4, 2)
        recommend_send = False
        fit_flags.append("Could not confirm a current affiliation — hard to contact or verify; low priority.")

    uncertainties: list[str] = []
    if institution == "Unknown":
        uncertainties.append("Current affiliation not confirmed — verify before contacting.")
    uncertainties.append("Email not resolved — scholarly APIs don't provide emails (never guessed).")

    return ProfessorCandidate(
        name=author.get("display_name") or seed["name"] or "(unknown)",
        title=None,
        department=None,
        institution=institution,
        institution_ror=institution_ror,
        profile_url=author.get("id"),
        research_summary=(
            f"Active on {topic_display}: {count} recent paper(s) on this topic"
            + (f"; h-index {h_index}" if h_index is not None else "")
            + "."
        ),
        recent_work=papers,
        fit_rationale=f"{count} recent paper(s) on {topic_display} (2024+); seniority={seniority}.",
        fit_score=fit_score,
        h_index=h_index,
        works_count=works_count,
        seniority=seniority,
        recommend_send=recommend_send,
        fit_flags=fit_flags,
        contact_email=None,
        email_source=None,
        email_verified=False,
        evidence=evidence,
        uncertainties=uncertainties,
    )


async def discover_professors(
    student: StudentProfile,
    goal: OutreachGoal,
    *,
    limit: int = 8,
    client: OpenAlexClient | None = None,
) -> DiscoveryResult:
    """End-to-end grounded discovery. Returns real professors with real cited recent work.

    NOTE: this is the discovery half. Fit-gating/ranking (docs/engine-design.md §1),
    email resolution (§2), and drafting/verification (§4) build on top of this.
    """
    owns_client = client is None
    client = client or OpenAlexClient(api_key=os.getenv("OPENALEX_API_KEY"))
    try:
        topics = await resolve_topic(client, goal.topic)
        if topics:
            topic_label = topics[0]["display_name"]
            topic_id_for_enrich = _short_id(topics[0]["id"])
            search_for_enrich = None
            seeds = await find_candidate_seeds(client, topic_id=topic_id_for_enrich)
            query_note = f"openalex_topic:{topic_label}"
        else:
            # No matching Topic (common for multi-word phrases) → keyword works search.
            topic_label = goal.topic
            topic_id_for_enrich = None
            search_for_enrich = goal.topic
            seeds = await find_candidate_seeds(client, search=goal.topic)
            query_note = f"openalex_works_search:{goal.topic}"

        if not seeds:
            return DiscoveryResult(
                goal=goal, candidates=[], queries_used=[goal.topic, query_note],
                sources=["openalex"], generated_at=_now(),
            )
        ranked = sorted(seeds.values(), key=lambda s: s["count"], reverse=True)[:limit]

        candidates: list[ProfessorCandidate] = []
        for seed in ranked:
            try:
                candidates.append(
                    await enrich_candidate(
                        client, seed, topic_label,
                        topic_id=topic_id_for_enrich, search_term=search_for_enrich,
                    )
                )
            except httpx.HTTPError:
                continue  # skip a candidate that fails to enrich rather than fail the whole run
        candidates.sort(key=lambda c: c.fit_score, reverse=True)

        # Collapse duplicates (same name + institution = one person split across OpenAlex IDs).
        seen_person: set[tuple[str, str]] = set()
        deduped_cands: list[ProfessorCandidate] = []
        for c in candidates:
            key = (c.name.lower(), c.institution.lower())
            if key in seen_person:
                continue
            seen_person.add(key)
            deduped_cands.append(c)
        candidates = deduped_cands

        return DiscoveryResult(
            goal=goal,
            candidates=candidates,
            queries_used=[goal.topic, query_note],
            sources=["openalex"],
            generated_at=_now(),
        )
    finally:
        if owns_client:
            await client.aclose()
